name = "Survivor season rankings"

[[extensionPoints]]
id = "Watch::Series::Details"
[[extensionPoints.conditions]]
series = "gid://watch/Series/96231fe2-2015-4685-888e-5a1eff501189"

[[extensionPoints]]
id = "Watch::Season::Details"
[[extensionPoints.conditions]]
series = "gid://watch/Series/96231fe2-2015-4685-888e-5a1eff501189"

[[extensionPoints]]
id = "Watch::WatchThrough::Details"
[[extensionPoints.conditions]]
series = "gid://watch/Series/96231fe2-2015-4685-888e-5a1eff501189"
