name = "Survivor season rankings"

[[extensionPoints]]
id = "Series.Details.RenderAccessory"
module = "features/SeriesDetails.tsx"
[[extensionPoints.conditions]]
series = "gid://watch/Series/96231fe2-2015-4685-888e-5a1eff501189"

[[extensionPoints]]
id = "Season.Details.RenderAccessory"
module = "features/SeasonDetails.tsx"
[[extensionPoints.conditions]]
series = "gid://watch/Series/96231fe2-2015-4685-888e-5a1eff501189"

[[extensionPoints]]
id = "WatchThrough.Details.RenderAccessory"
module = "features/WatchThroughDetails.tsx"
[[extensionPoints.conditions]]
series = "gid://watch/Series/96231fe2-2015-4685-888e-5a1eff501189"
