name = "Survivor season rankings"

[[extensionPoints]]
id = "Series.Details.RenderAccessory"
module = "features/SeriesDetails.tsx"
[[extensionPoints.conditions]]
series.handle = "survivor"

[[extensionPoints]]
id = "Season.Details.RenderAccessory"
module = "features/SeasonDetails.tsx"
[[extensionPoints.conditions]]
series.handle = "survivor"

[[extensionPoints]]
id = "WatchThrough.Details.RenderAccessory"
module = "features/WatchThroughDetails.tsx"

[[extensionPoints.conditions]]
series.handle = "survivor"
