name = "Survivor season rankings"
handle = "survivor-season-rankings"

[[extends]]
target = "Series.Details.RenderAccessory"
module = "./features/SeasonDetails.tsx"
[[extends.conditions]]
series.handle = "survivor"

[[extends]]
target = "Season.Details.RenderAccessory"
module = "./features/SeriesDetails.tsx"
[[extends.conditions]]
series.handle = "survivor"

[[extends]]
target = "WatchThrough.Details.RenderAccessory"
module = "./features/WatchThroughDetails.tsx"
[[extends.conditions]]
series.handle = "survivor"
