name = "Survivor season rankings"
handle = "survivor-season-rankings"

[[extends]]
target = "series.details.accessory"
module = "./features/SeriesDetails.tsx"
[[extends.conditions]]
series.handle = "survivor-14658"

[[extends]]
target = "watch-through.details.accessory"
module = "./features/WatchThroughDetails.tsx"
[[extends.conditions]]
series.handle = "survivor-14658"
