name = "Survivor winner pick"
handle = "survivor-winner-pick"

[[extends]]
target = "series.details.accessory"
module = "./features/SeriesDetails.tsx"
query = "./features/SeriesDetailsQuery.graphql"
[[extends.conditions]]
series.handle = "survivor-14658"

[[extends]]
target = "watch-through.details.accessory"
module = "./features/WatchThroughDetails.tsx"
query = "./features/WatchThroughDetailsQuery.graphql"
[[extends.conditions]]
series.handle = "survivor-14658"

[settings]
# What episode must the user make their winner pick by?
[[settings.fields]]
id = "pickBy"
type = "number"
default = 2
label.translation = "settings.pickBy.label"

# Should you be able to change your winner pick after the fact?
[[settings.fields]]
id = "allowChanges"
type = "options"
default = "disallow"
options = [
  { value = "disallow", label.translation = "settings.allowChanges.disallow" },
  { value = "allow", label.translation = "settings.allowChanges.allow" },
  { value = "untilVotedOut", label.translation = "settings.allowChanges.untilVotedOut" },
]
label.translation = "settings.allowChanges.label"
