name = "Survivor winner pick"

[[extensionPoints]]
id = "Series.Details.RenderAccessory"
module = "features/SeriesDetails.tsx"
[[extensionPoints.conditions]]
series.handle = "survivor"

[[extensionPoints]]
id = "Season.Details.RenderAccessory"
module = "features/SeasonDetails.tsx"
[[extensionPoints.conditions]]
series.handle = "survivor"

[[extensionPoints]]
id = "WatchThrough.Details.RenderAccessory"
module = "features/WatchThroughDetails.tsx"
[[extensionPoints.conditions]]
series.handle = "survivor"

[userConfiguration]

# What episode must the user make their winner pick by?
[[userConfiguration.schema]]
key = "pickBy"
type = "number"
default = 2
label.translation = "configuration.pickBy.label"

# Should you be able to change your winner pick after the fact?
[[userConfiguration.schema]]
key = "allowChanges"
type = "options"
default = "disallow"
options = [
  { value = "disallow", label.translation = "configuration.allowChanges.disallow" },
  { value = "allow", label.translation = "configuration.allowChanges.allow" },
  { value = "untilVotedOut", label.translation = "configuration.allowChanges.untilVotedOut" },
]
label.translation = "configuration.allowChanges.label"
