name = "Survivor winner pick"
handle = "survivor-winner-pick"

[[extends]]
target = "Series.Details.RenderAccessory"
module = "./features/SeriesDetails.tsx"
[[extends.conditions]]
series.handle = "survivor"

[[extends]]
target = "Season.Details.RenderAccessory"
module = "./features/SeasonDetails.tsx"
[[extends.conditions]]
series.handle = "survivor"

[[extends]]
target = "WatchThrough.Details.RenderAccessory"
module = "./features/WatchThroughDetails.tsx"
[[extends.conditions]]
series.handle = "survivor"

[settings]
# What episode must the user make their winner pick by?
[[settings.fields]]
id = "pickBy"
type = "number"
default = 2
label.translation = "settings.pickBy.label"

# Should you be able to change your winner pick after the fact?
[[settings.fields]]
id = "allowChanges"
type = "options"
default = "disallow"
options = [
  { value = "disallow", label.translation = "settings.allowChanges.disallow" },
  { value = "allow", label.translation = "settings.allowChanges.allow" },
  { value = "untilVotedOut", label.translation = "settings.allowChanges.untilVotedOut" },
]
label.translation = "settings.allowChanges.label"
