name = "Survivor winner pick"

[[extensionPoints]]
id = "Watch::Series::Details"
[[extensionPoints.conditions]]
series = "gid://watch/Series/4bacc15b-0a69-4bf5-ad90-dd52113b667d"

[[extensionPoints]]
id = "Watch::Season::Details"
[[extensionPoints.conditions]]
series = "gid://watch/Series/4bacc15b-0a69-4bf5-ad90-dd52113b667d"

[[extensionPoints]]
id = "Watch::WatchThrough::Details"
[[extensionPoints.conditions]]
series = "gid://watch/Series/4bacc15b-0a69-4bf5-ad90-dd52113b667d"

[userConfiguration]

# What episode must the user make their winner pick by?
[[userConfiguration.schema]]
key = "pickBy"
type = "Number"
default = 2
label.translation = "configuration.pickBy.label"

# Should you be able to change your winner pick after the fact?
[[userConfiguration.schema]]
key = "allowChanges"
type = "Options"
default = "disallow"
options = [
  { value = "disallow", label.translation = "configuration.allowChanges.disallow" },
  { value = "allow", label.translation = "configuration.allowChanges.allow" },
  { value = "untilVotedOut", label.translation = "configuration.allowChanges.untilVotedOut" },
]
label.translation = "configuration.allowChanges.label"
