name = "Example DOM extension"
handle = "example-dom-extension"

[[extends]]
target = "series.details.accessory"
module = "./SeriesAccessory.ts"
query = "./SeriesQuery.graphql"
mutations = "./*Mutation.graphql"
loading.ui = "./StartAccessorySkeleton.html"

# [[extends.conditions]]
# series.handle = "survivor"
