name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: quilt-framework/action-prepare@v1

      - name: Build
        run: yarn run build

      - name: Publish
        run: yarn run publish
        env:
          WATCH_ACCESS_TOKEN: ${{ secrets.WATCH_ACCESS_TOKEN }}
