name: Deploy

on:
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks 📝
    uses: ./.github/workflows/checks.yml

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare

      - name: Build
        run: pnpm run build

      - name: Deploy to Cloudflare
        run: pnpm run wrangler pages publish ./app/build/public -- --project-name watch-survivor
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Watch
        run: pnpm run watchapp push && pnpm run watchapp publish
        env:
          WATCH_ACCESS_TOKEN: ${{ secrets.WATCH_ACCESS_TOKEN }}
