name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks 📝
    uses: ./.github/workflows/checks.yml

  deploy:
    name: Deploy 🚀
    needs: checks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare

      - name: Build
        run: pnpm run build

      - name: Deploy to Cloudflare
        run: pnpm wrangler pages publish ./app/build/public --project-name watch-survivor
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Watch
        run: pnpm watchapp push && pnpm watchapp publish
        env:
          WATCH_ACCESS_TOKEN: ${{ secrets.WATCH_ACCESS_TOKEN }}
